{% set version = "0.8" %}
{% set name = "oommfodt" %}
{% set sha256 = "a8b8d636fe6e9396cfb8351fa0bea8fd49b23966b3c0edbda4fd448b428d726f" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: pip install --no-deps .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - pandas
    - pytest
    - xlwt 
    - xlrd 
    - openpyxl

test:
  imports:
    - oommfodt
  commands:
    - python -c "import sys; import oommfodt as m; sys.exit(m.test())"

about:
  home: http://joommf.github.io/
  license: BSD 3-clause
  license_family: BSD
  license_file: LICENSE
  summary: Reading and analysing OOMMF odt files.
  doc_url: http://oommfodt.readthedocs.io
  dev_url: https://github.com/joommf/oommfodt

  description: |
    oommfodt provides tools to read Ooommf Data Table files (ODT)
    files.
    It is part of the Jupyter-OOMMF project (https://github.com/joommf
    and http://joommf.github.io).

extra:
  recipe-maintainers:
    - fangohr
    - marijanbeg
    - takluyver
    - davidcortesortuno
    - rpep
