{% set version = "0.8.3" %}
{% set name = "oommfodt" %}
{% set sha256 = "55430fa1f773e51ae08fa4ef18ecfd282f27688d2b3091e80d8e85b35bcb46f7" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  skip: True  # [py27]
  number: 1000
  script: pip install --no-deps .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - pandas
    - pytest

test:
  imports:
    - oommfodt
  commands:
    - python -c "import sys; import oommfodt as m; sys.exit(m.test())"

about:
  home: http://joommf.github.io/
  license: BSD 3-clause
  license_family: BSD
  license_file: LICENSE
  summary: Reading and analysing OOMMF odt files
  doc_url: http://oommfodt.readthedocs.io
  dev_url: https://github.com/joommf/oommfodt

  description: |
    oommfodt provides tools for reading and analysis of OOMMF odt files.

    It is part of the Jupyter-OOMMF project (https://github.com/joommf
    and http://joommf.github.io).

extra:
  recipe-maintainers:
    - marijanbeg
    - fangohr
    - takluyver
    - davidcortesortuno
    - rpep
