{% set version = "0.8.4" %}
{% set name = "oommfodt" %}
{% set sha256 = "3ea3fd9786b1bd89eae7753b67fd7c4b3f407cc1f87dc2f435b4803f382bc855" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: pip install --no-deps .

requirements:
  build:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pandas
    - numpy
    - pytest

test:
  imports:
    - oommfodt
  commands:
    - python -c "import sys; import oommfodt as m; sys.exit(m.test())"

about:
  home: http://joommf.github.io/
  license: BSD 3-clause
  license_family: BSD
  license_file: LICENSE
  summary: Reading and merging of OOMMF .odt files
  doc_url: http://oommfodt.readthedocs.io
  dev_url: https://github.com/joommf/oommfodt

  description: |
    oommfodt provides tools for reading and merging of OOMMF .odt files.

    It is part of the Jupyter-OOMMF project (https://github.com/joommf
    and http://joommf.github.io).

extra:
  recipe-maintainers:
    - marijanbeg
    - sergii-mamedov
    - fangohr
    - takluyver
    - rpep
    - davidcortesortuno
