appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: FZG1PJ39jJFhiEXbLpUuaZeia+1KSyrxGyeg2+lBbdOxFEbmqyAYrqnnLkRdL6qRHe1ju/yX4MoeUrBGwUKSZstx/4pf/4LbiYLvzRNznVFpLqb5DXxt6/1PBd60/y2a79ArYh6KG2/iNmGl+gCiBC3T+XECo+SB1fIppgabaHOqZH91qtoIP3zAgoGZGRhdpxCsmCMThbMAcVqr9uBGkhuZqCoNJ7Kk7MDOROjb1gbmBtP6lJgkjfS4aan60SdFHsJQxb3wEBIYy/aOHaiHxdHhjwo9oTNcMh4ikrInC+ctHGueq3zNC/zFGSNRV1an0zV/84VPax9jfE+V5rf4CByT0DqE9lrIIarE1LtNMxAhidE43H2TP0Utx+vRlkzLquLzb9LLMakixgySX2FMoQoNkjq04eSZ4Fi/D3h1N7Old9rt26mngS+W9J5MKY8P4oiX2zjv93VIWfu2TkXKlnkZy5v5+qoti74bgON/ij6K6ZMib8TenxCR46NxoEHAb6ozp50O5H1OGHQAnftwBJ+iPiRBTDXo0VDf3BtletucJk+g/yZoiaW8l7632NcbIebbEC6n4Sk3ym7b5boGtxVaIQl23RYo9SSzTIGEMxg06PKkYdXatQrxLEv2H9oKZEszF/HFZjUsgwntRBmWkhJJOtCukPHn6shjSVI9Ad8=}
provider:
  win: azure
