travis:
  secure:
    BINSTAR_TOKEN: aUQPep62GyvLypmF/tyIkBTTG88t675hTEsXz6fSkIO6xd2U8JVotaDCtmpgBr0qmvlEuzyLDLvItACQ9NFlWg5O9Yspk7RW9PuCM6dc8zcfytMqjttZAyn9wrOzy5XER1BKuBu2+zaKBUkXSMom+J9FS8wnoZ2jVOW94fhoeLoVMnN/Fpv1R9mqTcJ3ZksDwqdSq9O+dhpOg2zZiupXT9aRejQOzyY9NtLVVfzquYfTOR/kJ5j/sezkN2VoQSIYootyBLKEOM5C52PE76rhxxLjq/B8xccurTl9Wtx/0JbBknaRHEre7+82yBMh+g0BMZVrZxDwMa0OQhYOFJMsVfweCnvsgloDtSBeEIfLGsNacxUs1KPtkggHO+yWL2uNPwr5L2hQzmlxpONZuND2JW1tKVsNBBDjsrBFXAPYy7qf98jOam8uAmr7g0InacbHtRr+cv0e45BC6jSwkuj2pbVYXr4AtG/lQvyazef5WjMFEOtFcQnvQP8ncPQX7l9S/ypKPsNkIR8W+I0t9AyZ9heVkXEHRaj+y1pU1wM0/Zd8SrQ1LCIISy8DbH0gAvyLCU5oS/mvpB+X/XYujHlpKZgP11TIBtNX+XvCYRrxfNQnd1W7H3Xr+nQyInRnv5pgKPVhRB87QU+yH5H9cMBHe5fTuoEf3oRId5t3nY+oPn8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
